### PR TITLE
Encapsulate the Manage Object to Hide Internal Details

### PR DESCRIPTION
**Pull request by dvonthenen**
## Proposed changes

**NOTE:** This depends on https://github.com/deepgram-devs/deepgram-go-sdk/pull/86, https://github.com/deepgram-devs/deepgram-go-sdk/pull/87, https://github.com/deepgram-devs/deepgram-go-sdk/pull/88, https://github.com/deepgram-devs/deepgram-go-sdk/pull/103 and is targeted to `go-sdk-v1` release. Will rebase when dependent PRs are merged. The diff in this PR will look pretty nasty until subsequent depend PRs are merged first. Until these get merged, here is a better looking diff to track the changes between branches: https://github.com/dvonthenen/deepgram-go-sdk/compare/dv/prerecorded-object-definition...dvonthenen:deepgram-go-sdk:dv/manage-object-definition

Addresses https://github.com/deepgram-devs/deepgram-go-sdk/issues/104, https://github.com/deepgram-devs/deepgram-go-sdk/issues/105, https://github.com/deepgram-devs/deepgram-go-sdk/issues/106.

Implements more of an object-oriented approach to handling the Manage struct. This change implements the following:
- Fixes it so all REST plumbing is not hidden from the user in the `manage` functions
- Implements a example for every single API call within `manage`
  - `examples/balances`
  - `examples/invitations`
  - `examples/keys`
  - `examples/members`
  - `examples/prerecorded` (this was already there)
  - `examples/projects`
  - `examples/scopes`
  - `examples/streaming` (this was already there)
  - `examples/usage`
- Implements nesting the HTTP Error code into all errors return from REST calls
- Fixed Live Client to be similar to Prerecord/Manage when Initializing client

## Types of changes

What types of changes does your code introduce to the community Go SDK?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update or tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

PR https://github.com/deepgram-devs/deepgram-go-sdk/pull/86 handled the restructure of the project. This is the first PR to start refactoring and improving individual components in this new restructure. This PR handles just the Live Client and Live Client only. I am trying to reduce the amount of code change in this PR and each component will be handled one at a time.

Will squash the commits after the review is completed.

### CODE REVIEW

**Comment by dvonthenen** [comment]
Until these get merged, here is a better looking diff to track the changes between branches:
https://github.com/dvonthenen/deepgram-go-sdk/compare/dv/prerecorded-object-definition...dvonthenen:deepgram-go-sdk:dv/manage-object-definition

**Comment by SandraRodgers** [comment]
I tested the examples and they all work!

**Review by SandraRodgers — APPROVED** [review]

**Review by SandraRodgers — APPROVED** [review]

**Comment by dvonthenen** [comment]
Rebased and squashed. Ready for review again.

**Comment by dvonthenen** [comment]
going to break this PR into 3-4 smaller PRs. closing.

**Pull request closed without merging**
